### ISSUE TITLE
add pre-node-gyp precompiled binaries?

### ISSUE THREAD

**Issue by Pomax** [EyalAr/lwip#195] opened 2015-10-13 20:37 UTC
While .cpp files are super handy on unixy platforms, getting lwip compiled on windows every time `npm install` runs is extremely complicated. In order to solve that problem, `node-gyp` can work together with `pre-node-gyp`, https://www.npmjs.com/package/node-pre-gyp, so that rather than compiling from source, the prehook first checks if there is a compiled binary already available, and if so, just deploys that instead.

Adding this to `lwip` would make the lives of everyone who has to work cross-platform a *lot* easier.

**Comment by EyalAr** [comment] 2015-10-14 02:07
Indeed, that would be very useful.
Duplicate of #83

**Closed by EyalAr** 2015-10-14 02:07 UTC

**Comment by Pomax** [comment] 2015-10-14 03:59
on a small note: reason I opened this was because it looks like node-gyp fails now that we're on node 4.x -- there's a whole bunch of "wrong syntax/template/etc..." errors building against the more recent v8 (on windows, at least. not tried unix flavours yet)

**Comment by EyalAr** [comment] 2015-10-14 04:36
Are you using LWIP 0.0.8?

**Comment by Pomax** [comment] 2015-10-14 16:24
Yeah, lwip 0.0.8 with node 4.1.1 and npm 2.14.4. When installing on Windows 7 with VS2012, the result is the following (rather huge) pastbin: https://pastebin.mozilla.org/8849263

**Comment by Pomax** [comment] 2015-10-14 19:52
let me open this as new issue, actually, so it doesn't pollute a closed one.
