### ISSUE TITLE
Fails decoding some images

### ISSUE THREAD

**Issue by technicallyfeasible** [EyalAr/lwip#130] opened 2015-04-13 15:50 UTC
For some images, decoding fails either completely or stops in the middle. If I am using a resize on such images then part of the result is simply dark gray.

Original:
![wumo_50s_dinner](https://cloud.githubusercontent.com/assets/5169186/7119286/7958b68a-e1fc-11e4-9f19-ccee25f2d4ce.jpg)

Resized to cover 300x300 pixels:
![55159145da5fe6041fca127d](https://cloud.githubusercontent.com/assets/5169186/7119306/9bc6f484-e1fc-11e4-8153-ea137e62f05a.png)

The code I am using for processing is this:

    lwip.open(buffer, "jpg", function(image) {
        // fit image into 300x300 region and save as png
        var batch = image.batch().cover(300, 300);
        var buffer = batch.toBuffer("png", {compression: "high", transparency: false});
    });

I understand that the image might be corrupt in some way but other viewers have no problem with them.

**Comment by EyalAr** [comment] 2015-05-26 03:06
Works for me...

![111c](https://cloud.githubusercontent.com/assets/1146412/7804526/ea95199a-0396-11e5-8435-e5995977f059.png)


```
lwip.open(PathToImage, function(err, image) {
    var batch = image.batch().cover(300, 300);
    batch.writeFile(PathToOutput, {
        compression: "high",
        transparency: false
    }, function(err){
        //...
    });
});
```

**Comment by EyalAr** [comment] 2015-05-26 03:07
Closing for now. Let me know if you can help me reproduce the problem.

**Closed by EyalAr** 2015-05-26 03:07 UTC
