### ISSUE TITLE
We are trying to install this on our azure server. We can't compile the windows binaries as we all have MAC

### ISSUE THREAD

**Issue by ericrab** [EyalAr/lwip#127] opened 2015-04-02 14:45 UTC
Has anyone gotten around this?

**Comment by EyalAr** [comment] 2015-04-04 01:21
Seems like a duplicate of https://github.com/EyalAr/lwip/issues/79 and related to https://github.com/EyalAr/lwip/issues/83

**Closed by EyalAr** 2015-04-04 01:21 UTC
