### ISSUE TITLE
Not working properly on Node.js 4.0.0

### ISSUE THREAD

**Issue by pandres95** [EyalAr/lwip#184] opened 2015-09-21 17:53 UTC
Also reporting on https://github.com/nodejs/node/issues/2798 where you can get more information about this issue.

**Comment by cedon** [comment] 2015-09-25 01:49
I am having this same issue trying to install 'Sprity'

**Comment by antoinepairet** [comment] 2015-09-26 16:10
The issue comes from the NAN dependency which is currently at `1.8.4`. It should be upgraded to NAN `2.x`. The thread mentioned by @pandres95 provides a lot of info.
I would be glad to help. making the port happen.

**Comment by antoinepairet** [comment] 2015-09-26 16:12
This is a duplicate of #179

**Comment by EyalAr** [comment] 2015-10-03 06:18
See #182

**Closed by EyalAr** 2015-10-03 06:18 UTC
