### ISSUE TITLE
drawText feature

### ISSUE THREAD

**Issue by thellimist** [EyalAr/lwip#123] opened 2015-03-22 01:01 UTC
The feature where drawing texts should be added. 

image.batch()
        .drawText("Hello World", xCoord, yCoord, size)
        .writeFile(out, function(err) {
            if (err) return console.log(err);
            console.log('done');
        });

as for extra features related with this: 
.textColor(hexaColor)
.textPosition(Enum) (where enum is top, middle, bottom, topcentered, middlecentered, bottomcentered)
.textFont(fontPath)

**Comment by EyalAr** [comment] 2015-03-22 14:45
Duplicate of https://github.com/EyalAr/lwip/issues/54

**Closed by EyalAr** 2015-03-22 14:45 UTC
